# Основные настройки
homeassistant:
  name: Умный Дом
  latitude: 59.9041  
  longitude: 30.5094
  elevation: 11
  unit_system: metric
  time_zone: Europe/Moscow
  internal_url: "http://localhost:8123"

default_config:
  disable:
    - updater
    - mobile_app
    - cloud
    - discovery
    - ssdp
    - zeroconf

# Оптимизированные настройки MQTT
mqtt:
  broker: r62e666b.ala.eu-central-1.emqxsl.com
  port: 8883
  username: mqtt_user1
  password: RfNz3222281488
  discovery: false
  client_id: railway_ha_01
  keepalive: 60
  protocol: 3.1.1

# Жёстко ограничиваем логи
logger:
  default: error
  logs:
    homeassistant.components.mqtt: warning
    homeassistant.core: error

# Оптимизация памяти
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
