# Основные настройки
homeassistant:
  name: Умный Дом
  latitude: 59.9041
  longitude: 30.5094
  elevation: 11
  unit_system: metric
  time_zone: Europe/Moscow
  internal_url: "http://localhost:8123"

# Полное отключение DHCP и сетевого обнаружения
dhcp:
  enabled: false

default_config:
  disable:
    - updater
    - mobile_app
    - cloud
    - discovery
    - ssdp
    - zeroconf

# Корректная настройка MQTT с SSL
mqtt:
  broker: r62e666b.ala.eu-central-1.emqxsl.com
  port: 8883
  username: mqtt_user1
  password: RfNz3222281488
  discovery: false
  protocol: 3.1.1
  tls_insecure: false
  tls_version: '1.2'
  client_id: railway-ha-${HOSTNAME}
  keepalive: 60
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
    qos: 1
    retain: true

# Оптимизация логов
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info
    homeassistant.core: error
