# Основные настройки
homeassistant:
  name: Умный Дом
  latitude: 59.9041  
  longitude: 30.5094
  elevation: 11
  unit_system: metric
  time_zone: Europe/Moscow
  internal_url: "http://localhost:8123"

# Полностью отключаем проблемные компоненты
dhcp:
  enabled: false

default_config:
  disable:
    - updater
    - mobile_app
    - cloud
    - discovery  # Добавлено отключение автообнаружения
    - ssdp       # Отключаем поиск UPnP-устройств
    - zeroconf   # Отключаем mDNS

# Оптимизированные настройки MQTT
mqtt:
  broker: r62e666b.ala.eu-central-1.emqxsl.com
  port: 8883
  username: mqtt_user1
  password: RfNz3222281488
  discovery: false  # Отключаем MQTT Discovery (ручное добавление устройств)
  client_id: railway_ha_01  # Уникальный ID для подключения
  keepalive: 60  # Увеличиваем интервал keepalive
  protocol: 3.1.1  # Явно указываем версию MQTT

# Жёстко ограничиваем логи
logger:
  default: error  # Только ошибки по умолчанию
  logs:
    homeassistant.components.mqtt: warning
    homeassistant.core: error

# Оптимизация памяти
http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
