# Основные настройки
homeassistant:
  name: Умный Дом
  latitude: 59.9041  
  longitude: 30.5094
  elevation: 11
  unit_system: metric
  time_zone: Europe/Moscow
  internal_url: "http://localhost:8123"  

# Отключаем ненужные компоненты для экономии RAM
default_config:
  disable:
    - updater
    - mobile_app
    - cloud
    - dhcp 

# Включаем только необходимые интеграции
config:

# Настройки логгирования (уменьшаем нагрузку)
logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info  # Подробные логи только для MQTT

# MQTT (основное подключение)
mqtt:
  broker: r62e666b.ala.eu-central-1.emqxsl.com
  port: 8883
  username: mqtt_user1
  password: RfNz3222281488
  discovery: true

# Группы для интерфейса
group:
  default_view:
    view: yes
    entities:
      - sensor.temperature_in_room
      - switch.light_in_room
